naver:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    bucket-name: bitcamp-auction

---
spring:
  config:
    activate:
      on-profile: common-local
---
spring:
  config:
    activate:
      on-profile: common-dev
